name: test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run Linters
        working-directory: ./python
        run: tox -e lint
  type-checks:
    runs-on: ubuntu-latest
    name: Type Checks
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run Type Checks
        working-directory: ./python
        run: tox -e type-check
