name: build
on:
  push:
    branches: '*'
jobs:
  build-docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Git
        run: 'sudo apt-get install -y git'
      - name: Test Git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git tag
          git describe
      - name: Copy Requirements
        uses: canastro/copy-file-action@master
        with:
          source: "python/requirements.txt"
          target: "docs/requirements.txt"
      - name: Build HTML
        uses: ammaraskar/sphinx-action@0.4
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html

  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Set Spark env
      run: |
        export SPARK_LOCAL_IP=127.0.0.1
        export SPARK_SUBMIT_OPTS="--illegal-access=permit -Dio.netty.tryReflectionSetAccessible=true"
    - name: Generate coverage report
      working-directory: ./python
      run: |
        pip install -r requirements.txt
        pip install coverage
        coverage run -m unittest discover -s tests -p '*_tests.py'
        coverage xml
    - name: Publish test coverage
      uses: codecov/codecov-action@v1
